import logging

from models.theatre import TheatreModel
from models.movie import MovieModel
from models.schedule import ScheduleModel
from models.user import UserModel
from db import db

logger = logging.getLogger(__name__)
logger.info("Populating data in database")


def initialize_db():
    user1 = UserModel(name="admin", type="admin")
    user2 = UserModel(name="owner", type="owner")
    user3 = UserModel(name="user", type="user")
    db.session.add(user1)
    db.session.add(user2)
    db.session.add(user3)
    db.session.commit()

    th1 = TheatreModel(name="theatre1", screens=2, location="hyd")
    th2 = TheatreModel(name="theatre2", screens=4, location="hyd")
    th3 = TheatreModel(name="theatre3", screens=1, location="hyd")
    th4 = TheatreModel(name="test", screens=1, location="hyd")
    db.session.add(th1)
    db.session.add(th2)
    db.session.add(th3)
    db.session.add(th4)

    mv1 = MovieModel(name="avengers1", genre="gnr1")
    mv2 = MovieModel(name="avengers2", genre="gnr2")
    mv3 = MovieModel(name="avengers3", genre="gnr1")
    mv4 = MovieModel(name="avengers4", genre="gnr3")
    mv5 = MovieModel(name="test", genre="gnr3")
    db.session.add(mv1)
    db.session.add(mv2)
    db.session.add(mv3)
    db.session.add(mv4)
    db.session.add(mv5)

    db.session.commit()

    sch1 = ScheduleModel(movie_id=mv1.id, theatre_id=th1.id, screen=1, time="11:30")
    sch2 = ScheduleModel(movie_id=mv2.id, theatre_id=th1.id, screen=2, time="11:50")
    sch3 = ScheduleModel(movie_id=mv3.id, theatre_id=th1.id, screen=1, time="14:30")
    sch4 = ScheduleModel(movie_id=mv2.id, theatre_id=th1.id, screen=1, time="16:15")
    sch5 = ScheduleModel(movie_id=mv4.id, theatre_id=th1.id, screen=2, time="19:00")
    sch6 = ScheduleModel(movie_id=mv2.id, theatre_id=th1.id, screen=1, time="20:30")
    sch7 = ScheduleModel(movie_id=mv1.id, theatre_id=th1.id, screen=2, time="23:30")
    sch8 = ScheduleModel(movie_id=mv4.id, theatre_id=th1.id, screen=2, time="21:05")

    sch9 = ScheduleModel(movie_id=mv4.id, theatre_id=th2.id, screen=1, time="10:45")
    sch10 = ScheduleModel(movie_id=mv3.id, theatre_id=th2.id, screen=1, time="13:50")
    sch11 = ScheduleModel(movie_id=mv3.id, theatre_id=th2.id, screen=1, time="18:35")
    sch12 = ScheduleModel(movie_id=mv2.id, theatre_id=th2.id, screen=1, time="21:30")
    sch13 = ScheduleModel(movie_id=mv1.id, theatre_id=th2.id, screen=2, time="11:05")
    sch14 = ScheduleModel(movie_id=mv4.id, theatre_id=th2.id, screen=2, time="15:00")
    sch15 = ScheduleModel(movie_id=mv4.id, theatre_id=th2.id, screen=2, time="19:30")
    sch16 = ScheduleModel(movie_id=mv2.id, theatre_id=th2.id, screen=2, time="22:00")
    sch17 = ScheduleModel(movie_id=mv1.id, theatre_id=th2.id, screen=3, time="10:15")
    sch18 = ScheduleModel(movie_id=mv1.id, theatre_id=th2.id, screen=3, time="14:30")
    sch19 = ScheduleModel(movie_id=mv2.id, theatre_id=th2.id, screen=3, time="17:30")
    sch20 = ScheduleModel(movie_id=mv2.id, theatre_id=th2.id, screen=3, time="23:30")
    sch21 = ScheduleModel(movie_id=mv4.id, theatre_id=th2.id, screen=4, time="09:30")
    sch22 = ScheduleModel(movie_id=mv1.id, theatre_id=th2.id, screen=4, time="12:30")
    sch23 = ScheduleModel(movie_id=mv3.id, theatre_id=th2.id, screen=4, time="16:50")
    sch24 = ScheduleModel(movie_id=mv4.id, theatre_id=th2.id, screen=4, time="20:50")

    sch25 = ScheduleModel(movie_id=mv4.id, theatre_id=th3.id, screen=4, time="10:35")
    sch26 = ScheduleModel(movie_id=mv3.id, theatre_id=th3.id, screen=4, time="13:15")
    sch27 = ScheduleModel(movie_id=mv4.id, theatre_id=th3.id, screen=4, time="16:05")
    sch28 = ScheduleModel(movie_id=mv1.id, theatre_id=th3.id, screen=4, time="21:50")

    db.session.add(sch1)
    db.session.add(sch2)
    db.session.add(sch3)
    db.session.add(sch4)
    db.session.add(sch5)
    db.session.add(sch6)
    db.session.add(sch7)
    db.session.add(sch8)
    db.session.add(sch9)
    db.session.add(sch10)
    db.session.add(sch11)
    db.session.add(sch12)
    db.session.add(sch13)
    db.session.add(sch14)
    db.session.add(sch15)
    db.session.add(sch16)
    db.session.add(sch17)
    db.session.add(sch18)
    db.session.add(sch19)
    db.session.add(sch20)
    db.session.add(sch21)
    db.session.add(sch22)
    db.session.add(sch23)
    db.session.add(sch24)
    db.session.add(sch25)
    db.session.add(sch26)
    db.session.add(sch27)
    db.session.add(sch28)

    db.session.commit()